package Vista;
import Controlador.ControladorCombate;
import Controlador.ControladorPrincipal;
import Modelo.Pokemon;
import javax.swing.JOptionPane;
public class VistaCombate extends javax.swing.JDialog {
    
    int op1;
    int op2;
    private ControladorCombate cc;
    private ControladorPrincipal cp;
    String[] equipoTest1;
    String[] equipoTest2;
    Pokemon[] equipo1;
    Pokemon[] equipo2;
    //Pokemones creados para la prueba
    
    /**
     * Creates new form VentanaCombate
     */
    public VistaCombate(ControladorCombate cco, ControladorPrincipal op,String usu1, String usu2, Pokemon[] equipo, Pokemon[] equipo2) {
        initComponents();
        this.cp = op;
        this.cc = cco;
        this.equipo1 = equipo;
        this.equipo2 = equipo2;
        System.out.println(equipo1[0].getNombre()+ " "+ equipo2[0].getNombre());
        String[] ataquesp1=cc.asignaA(equipo);
        String[] ataquesp2=cc.asignaA(equipo);
        ataques1.setModel(new javax.swing.DefaultComboBoxModel(ataquesp1));
        ataques1.setEnabled(false);
        ataques2.setModel(new javax.swing.DefaultComboBoxModel(ataquesp2));
        ataques2.setEnabled(false);
        equipoTest1 = cc.asignaP(equipo);
        equipoTest2 = cc.asignaP(equipo);
        pokemon1.setModel(new javax.swing.DefaultComboBoxModel(equipoTest1));
        pokemon1.setEnabled(false);
        pokemon2.setModel(new javax.swing.DefaultComboBoxModel(equipoTest2));
        pokemon2.setEnabled(false);
        pokemonActivo1.setText(equipo1[0].getNombre());
        pokemonActivo2.setText(equipo2[0].getNombre());
        usuv1.setText(usu1);
        usuv2.setText(usu2);
        Hp1.setText(Integer.toString(equipo1[0].getPS()));
        Hp2.setText(Integer.toString(equipo2[0].getPS()));
    }   

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usuv1 = new javax.swing.JLabel();
        ataques1 = new javax.swing.JComboBox();
        pokemon1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        usuv2 = new javax.swing.JLabel();
        ataques2 = new javax.swing.JComboBox();
        pokemon2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pokemonActivo1 = new javax.swing.JLabel();
        pokemonActivo2 = new javax.swing.JLabel();
        Hp1 = new javax.swing.JLabel();
        Hp2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Vista Combate");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(147, 31, 69, 14);

        usuv1.setText("Usuario1");
        getContentPane().add(usuv1);
        usuv1.setBounds(10, 67, 42, 14);

        ataques1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ataques1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ataques1ActionPerformed(evt);
            }
        });
        getContentPane().add(ataques1);
        ataques1.setBounds(91, 113, 56, 20);

        pokemon1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pokemon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokemon1ActionPerformed(evt);
            }
        });
        getContentPane().add(pokemon1);
        pokemon1.setBounds(261, 113, 56, 20);

        jLabel3.setText("HP: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(116, 155, 20, 14);

        jLabel4.setText("Ataque");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(52, 116, 35, 14);

        jLabel5.setText("Pokémon");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(208, 116, 43, 14);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 238, 400, 10);

        usuv2.setText("Usuario2");
        getContentPane().add(usuv2);
        usuv2.setBounds(10, 266, 42, 14);

        ataques2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ataques2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ataques2ActionPerformed(evt);
            }
        });
        getContentPane().add(ataques2);
        ataques2.setBounds(75, 323, 56, 20);

        pokemon2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(pokemon2);
        pokemon2.setBounds(255, 323, 56, 20);

        jLabel7.setText("Ataque");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 326, 35, 14);

        jLabel8.setText("Pokemon");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(208, 326, 43, 14);

        jLabel9.setText("HP:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(114, 379, 17, 14);

        jButton1.setText("SimularTurno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(149, 428, 95, 23);

        jButton2.setText("Atacar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(91, 63, 65, 23);

        jButton3.setText("Cambiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(261, 63, 71, 23);

        jButton4.setText("Atacar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(67, 282, 65, 23);

        jButton5.setText("Cambiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(249, 282, 71, 23);

        pokemonActivo1.setText("jLabel10");
        getContentPane().add(pokemonActivo1);
        pokemonActivo1.setBounds(10, 155, 40, 14);

        pokemonActivo2.setText("jLabel10");
        getContentPane().add(pokemonActivo2);
        pokemonActivo2.setBounds(41, 379, 40, 14);

        Hp1.setText("HP1");
        getContentPane().add(Hp1);
        Hp1.setBounds(173, 151, 66, 23);

        Hp2.setText("hp2");
        getContentPane().add(Hp2);
        Hp2.setBounds(178, 375, 40, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VistaCombate2.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pokemon1.setEnabled(false);
        ataques1.setEnabled(true);
        op1 = 1;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       pokemon1.setEnabled(true);
       ataques1.setEnabled(false);
       op1 = 2;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        pokemon2.setEnabled(false);
        ataques2.setEnabled(true);
        op2 = 1;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        pokemon2.setEnabled(true);
        ataques2.setEnabled(false);
        op2 = 2;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void pokemon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokemon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pokemon1ActionPerformed

    private void ataques1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ataques1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ataques1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //String ataquej1 = (String) ataques1.getSelectedItem();
        //String ataquej2 = (String) ataques2.getSelectedItem();
        //String cambioj1 = (String) pokemon1.getSelectedItem();
        //String cambioj2 = (String) pokemon2.getSelectedItem();
        System.out.println("opcion J1:" + op1 + "opcion j2" + op2);
        if(op1==0 && op2==0){
            JOptionPane.showMessageDialog(null, "DEBE HACER SELECCION EN AMBOS JUGADORES");
        }
        else{
            equipo1=cc.realizarAccion(op1,pokemon1.getSelectedIndex(),equipo1,equipo2,ataques1.getSelectedIndex());
            equipo2=cc.realizarAccion(op2,pokemon2.getSelectedIndex(),equipo2,equipo1, ataques2.getSelectedIndex());
            pokemonActivo1.setText(equipo1[0].getNombre());
            pokemonActivo2.setText(equipo2[0].getNombre());
            Hp1.setText(Integer.toString(equipo1[0].getPS()));
            Hp2.setText(Integer.toString(equipo2[0].getPS()));
            op1=0;
            op2=0;
            pokemon1.setEnabled(false);
            pokemon2.setEnabled(false);
            ataques1.setEnabled(false);
            ataques2.setEnabled(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ataques2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ataques2ActionPerformed
        
    }//GEN-LAST:event_ataques2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hp1;
    private javax.swing.JLabel Hp2;
    private javax.swing.JComboBox ataques1;
    private javax.swing.JComboBox ataques2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox pokemon1;
    private javax.swing.JComboBox pokemon2;
    private javax.swing.JLabel pokemonActivo1;
    private javax.swing.JLabel pokemonActivo2;
    private javax.swing.JLabel usuv1;
    private javax.swing.JLabel usuv2;
    // End of variables declaration//GEN-END:variables
}
